meshConfig:
  accessLogFile: /dev/stdout
  extensionProviders:
  - name: oauth2-proxy
    envoyExtAuthzHttp:
      service: oauth2-proxy.oauth2-proxy.svc.cluster.local
      port: 4180
      includeRequestHeadersInCheck:
      - cookie
      headersToUpstreamOnAllow:
      - authorization
      headersToDownstreamOnDeny:
      - set-cookie
