apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PeerAuthentication.yaml
  - namespace.yaml
  - workload.yaml
  - Certificate.yaml
  - Routing.yaml
patches:
  - target:
      kind: Gateway
      name: demo
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - demo/demo1.digihunch.com
  - target:
      kind: VirtualService
      name: demo
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - demo1.digihunch.com
  - target:
      kind: Certificate
      name: demo
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
        - demo1.digihunch.com
