apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo 
  template:
    metadata:
      labels:
        app: demo 
    spec:
      containers:
      - name: aks-helloworld-one
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"
---
apiVersion: v1
kind: Service
metadata:
  name: demo 
  namespace: demo
spec:
  ports:
  - name: http-demo
    port: 80
  selector:
    app: demo 
