apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PeerAuthentication.yaml
  - namespace.yaml
  - workload.yaml
  - Certificate.yaml
  - Routing.yaml
  - Auth.yaml
patches:
  - target:
      kind: Gateway
      name: demo
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts
        value:
        - demo/demo1.digihunch.com
  - target:
      kind: VirtualService
      name: demo
    patch: |-
      - op: replace
        path: /spec/hosts
        value:
        - demo1.digihunch.com
  - target:
      kind: Certificate
      name: demo
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
        - demo1.digihunch.com
  - target:
      kind: RequestAuthentication
      name: istio-ingressgateway
    patch: |-
      - op: replace
        path: /spec/jwtRules/0/issuer
        value: https://accounts.google.com
  - target:
      kind: RequestAuthentication
      name: istio-ingressgateway
    patch: |-
      - op: replace
        path: /spec/jwtRules/0/jwksUri
        value: https://www.googleapis.com/oauth2/v3/certs
