apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - demo/demo.digihunch.com
    tls:
      credentialName: demo-tls
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo
  namespace: demo
spec:
  hosts:
  - demo.digihunch.com
  gateways:
  - istio-system/demo
  http:
  - route:
    - destination:
        port:
          number: 80
        host: demo
